In [1]:
###Data analytics
import numpy as np
import pandas as pd

###Data visualization
import matplotlib.pyplot as plt

###Standard Scalar
from sklearn.preprocessing import StandardScaler

###KNN
from sklearn.neighbors import KNeighborsClassifier

###Perfomance metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score, classification_report

In [2]:
### Load the data
df_train = pd.read_csv('/content/train_KNN.csv')
df_test = pd.read_csv('/content/test_KNN.csv')

In [3]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [7]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
mp = 100*(df_train.isnull().sum()/len(df_train))
mp

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [8]:
mp = mp[mp>0].sort_values()

In [9]:
mp

Embarked     0.224467
Age         19.865320
Cabin       77.104377
dtype: float64

In [10]:
df_train["Age"].median()

28.0

In [11]:
df_train["Fare"].median()

14.4542

In [12]:
df_train[df_train["Embarked"].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [13]:
df_train = df_train.dropna(axis = 0, subset = ["Embarked"] )

In [14]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.3+ KB

In [15]:
df_train["Age"] = df_train["Age"].fillna(df_train["Age"].median())

In [16]:
df_train = df_train.drop(["Cabin"], axis = 1) # 1 is for column

In [25]:
###Testing
mpt = 100*(df_test.isnull().sum()/len(df_test))
mpt

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [26]:
mpt = mpt[mpt>0].sort_values()
mpt

Fare      0.239234
Age      20.574163
Cabin    78.229665
dtype: float64

In [27]:
df_test[df_test["Fare"].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
152,1044,0,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S

In [28]:
df_test = df_test.dropna(axis = 0, subset = ["Fare"])

In [29]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 417 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  417 non-null    int64
 1   Survived     417 non-null    int64
 2   Pclass       417 non-null    int64
 3   Name         417 non-null    object
 4   Sex          417 non-null    object
 5   Age          331 non-null    float64
 6   SibSp        417 non-null    int64
 7   Parch        417 non-null    int64
 8   Ticket       417 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     417 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 42.4+ KB

In [33]:
df_test["Age"] = df_test["Age"].fillna(df_test["Age"].median())

In [44]:
df_train.drop(["PassengerId", "Name", "Ticket"], axis = 1 , inplace = True)

KeyError: "['PassengerId', 'Name', 'Ticket'] not found in axis"

In [ ]:
df_train["Survived"] + df_train["Survived"].apply(str)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
df_train["Pclass"] = df_train["Pclass"].apply(str)

In [ ]:
df_test["Survived"] = df_test["Survived"].apply(str)
df_test["Pclass"] = df_test["Pclass"].apply(str)

In [40]:
df_train_num = df_train.select_dtypes(exclude = "object")
df_train_obj = df_train.select_dtypes(include = "object")
df_train_obj = pd.get_dummies(df_train_obj, drop_first = True) # Dummify categorical columns
Final_train_df = pd.concat([df_train_num, df_train_obj], axis = 1)

In [ ]:
df_train_num.columns

Index(['PassengerId', 'Survived', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
# This cell is no longer needed as dummification is now handled in cell r7YTJ5yj4UW7

In [ ]:
df_test_obj = df_test.select_dtypes(include = "object")
df_test_obj = pd.get_dummies(df_test_obj, drop_first = True)

In [ ]:
df_test_obj.columns

Index(['Survived_1', 'Pclass_2', 'Pclass_3',
       'Name_Abbott, Mr. Rossmore Edward',
       'Name_Abbott, Mrs. Stanton (Rosa Hunt)', 'Name_Abelson, Mr. Samuel',
       'Name_Abelson, Mrs. Samuel (Hannah Wizosky)',
       'Name_Adahl, Mr. Mauritz Nils Martin', 'Name_Adams, Mr. John',
       'Name_Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
       ...
       'Ticket_W./C. 14258', 'Ticket_W./C. 14263', 'Ticket_W./C. 6607',
       'Ticket_W./C. 6608', 'Ticket_W./C. 6609', 'Ticket_W.E.P. 5734',
       'Ticket_W/C 14208', 'Ticket_WE/P 5735', 'Embarked_Q', 'Embarked_S'],
      dtype='object', length=1576)

In [ ]:
df_test_num = df_test.select_dtypes(exclude = "object")
Final_test_df = pd.concat([df_test_num, df_test_obj, df_test["Survived"]], axis = 1)
Final_test_df.head()

,PassengerId,Age,SibSp,Parch,Fare,Survived_1,Pclass_2,Pclass_3,"Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)",...,Ticket_W./C. 14263,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W./C. 6609,Ticket_W.E.P. 5734,Ticket_W/C 14208,Ticket_WE/P 5735,Embarked_Q,Embarked_S,Survived
0,1,22.0,1,0,7.2500,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,0
1,2,38.0,1,0,71.2833,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
2,3,26.0,0,0,7.9250,True,False,True,False,False,...,False,False,False,False,False,False,False,False,True,1
3,4,35.0,1,0,53.1000,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,1
4,5,35.0,0,0,8.0500,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,0

In [ ]:
X_train = Final_train_df.drop("Survived", axis = 1)

NameError: name 'Final_train_df' is not defined

In [ ]:
y_train = Final_train_df["Survived"]

NameError: name 'Final_train_df' is not defined

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

NameError: name 'X_train' is not defined

In [ ]:
plt.plot(range(1,30), Performance_Metric)

NameError: name 'Performance_Metric' is not defined